import { VariableName } from '../types';

export type LawCategory =
  | 'De Morgan'
  | 'Distributive'
  | 'Conditionals'
  | 'Basic Equivalences'
  | 'Absorption'
  | 'Biconditional & XOR'
  | 'Rules of Inference';

export interface LogicLaw {
  id: string;
  name: string;
  category: LawCategory;
  symbolicFormula: string;
  lhs: string;
  rhs: string;
  tautologyExpression: string;
  variables: VariableName[];
  meaning: string;
  intuition: string;
  evalLhs: (p: boolean, q: boolean, r: boolean) => boolean;
  evalRhs: (p: boolean, q: boolean, r: boolean) => boolean;
}

export const LOGIC_LAWS: LogicLaw[] = [
  // --- De Morgan's Laws ---
  {
    id: 'demorgan-conjunction',
    name: "De Morgan's First Law (Negation of Conjunction)",
    category: 'De Morgan',
    symbolicFormula: '¬(p ∧ q) ≡ ¬p ∨ ¬q',
    lhs: '¬(p ∧ q)',
    rhs: '¬p ∨ ¬q',
    tautologyExpression: '¬(p ∧ q) ↔ (¬p ∨ ¬q)',
    variables: ['p', 'q'],
    meaning: 'The negation of a conjunction is equivalent to the disjunction of the negations.',
    intuition: 'If it is NOT the case that both p and q are true, then at least one of them must be false.',
    evalLhs: (p, q) => !(p && q),
    evalRhs: (p, q) => !p || !q,
  },
  {
    id: 'demorgan-disjunction',
    name: "De Morgan's Second Law (Negation of Disjunction)",
    category: 'De Morgan',
    symbolicFormula: '¬(p ∨ q) ≡ ¬p ∧ ¬q',
    lhs: '¬(p ∨ q)',
    rhs: '¬p ∧ ¬q',
    tautologyExpression: '¬(p ∨ q) ↔ (¬p ∧ ¬q)',
    variables: ['p', 'q'],
    meaning: 'The negation of a disjunction is equivalent to the conjunction of the negations.',
    intuition: 'If neither p nor q is true, then both p is false and q is false.',
    evalLhs: (p, q) => !(p || q),
    evalRhs: (p, q) => !p && !q,
  },

  // --- Distributive Laws ---
  {
    id: 'distributive-and-over-or',
    name: 'Distributive Law (AND over OR)',
    category: 'Distributive',
    symbolicFormula: 'p ∧ (q ∨ r) ≡ (p ∧ q) ∨ (p ∧ r)',
    lhs: 'p ∧ (q ∨ r)',
    rhs: '(p ∧ q) ∨ (p ∧ r)',
    tautologyExpression: '(p ∧ (q ∨ r)) ↔ ((p ∧ q) ∨ (p ∧ r))',
    variables: ['p', 'q', 'r'],
    meaning: 'Conjunction distributes over disjunction, analogous to multiplication distributing over addition.',
    intuition: 'For p AND (q or r) to be true, p must be true along with either q or r.',
    evalLhs: (p, q, r) => p && (q || r),
    evalRhs: (p, q, r) => (p && q) || (p && r),
  },
  {
    id: 'distributive-or-over-and',
    name: 'Distributive Law (OR over AND)',
    category: 'Distributive',
    symbolicFormula: 'p ∨ (q ∧ r) ≡ (p ∨ q) ∧ (p ∨ r)',
    lhs: 'p ∨ (q ∧ r)',
    rhs: '(p ∨ q) ∧ (p ∨ r)',
    tautologyExpression: '(p ∨ (q ∧ r)) ↔ ((p ∨ q) ∧ (p ∨ r))',
    variables: ['p', 'q', 'r'],
    meaning: 'Disjunction distributes over conjunction (unlike addition over multiplication in arithmetic).',
    intuition: 'If either p is true or both q and r are true, then in both cases (p or q) and (p or r) will hold.',
    evalLhs: (p, q, r) => p || (q && r),
    evalRhs: (p, q, r) => (p || q) && (p || r),
  },

  // --- Conditional / Implication Laws ---
  {
    id: 'material-implication',
    name: 'Law of Material Implication',
    category: 'Conditionals',
    symbolicFormula: 'p → q ≡ ¬p ∨ q',
    lhs: 'p → q',
    rhs: '¬p ∨ q',
    tautologyExpression: '(p → q) ↔ (¬p ∨ q)',
    variables: ['p', 'q'],
    meaning: 'A conditional statement p → q is logically equivalent to ¬p ∨ q.',
    intuition: 'The promise p → q is only broken when p is True and q is False. Otherwise, either p was False or q came true.',
    evalLhs: (p, q) => !p || q,
    evalRhs: (p, q) => !p || q,
  },
  {
    id: 'contrapositive',
    name: 'Law of the Contrapositive',
    category: 'Conditionals',
    symbolicFormula: 'p → q ≡ ¬q → ¬p',
    lhs: 'p → q',
    rhs: '¬q → ¬p',
    tautologyExpression: '(p → q) ↔ (¬q → ¬p)',
    variables: ['p', 'q'],
    meaning: 'A conditional statement is equivalent to its contrapositive. Backbone of indirect proofs.',
    intuition: 'If "raining implies wet ground", then "dry ground implies it is not raining".',
    evalLhs: (p, q) => !p || q,
    evalRhs: (p, q) => !(!q) || !p,
  },
  {
    id: 'negation-of-conditional',
    name: 'Negation of a Conditional',
    category: 'Conditionals',
    symbolicFormula: '¬(p → q) ≡ p ∧ ¬q',
    lhs: '¬(p → q)',
    rhs: 'p ∧ ¬q',
    tautologyExpression: '¬(p → q) ↔ (p ∧ ¬q)',
    variables: ['p', 'q'],
    meaning: 'The only way to disprove an implication is having the hypothesis true while the conclusion is false.',
    intuition: 'To prove a broken promise "if you help me, I will pay you", you must help AND not get paid.',
    evalLhs: (p, q) => !(!p || q),
    evalRhs: (p, q) => p && !q,
  },
  {
    id: 'exportation',
    name: 'Law of Exportation',
    category: 'Conditionals',
    symbolicFormula: '(p ∧ q) → r ≡ p → (q → r)',
    lhs: '(p ∧ q) → r',
    rhs: 'p → (q → r)',
    tautologyExpression: '((p ∧ q) → r) ↔ (p → (q → r))',
    variables: ['p', 'q', 'r'],
    meaning: 'Currying in logic: establishing two conditions together leading to r is equivalent to establishing them sequentially.',
    intuition: 'If both working hard and having luck leads to success, then if you work hard, luck leads to success.',
    evalLhs: (p, q, r) => !(p && q) || r,
    evalRhs: (p, q, r) => !p || (!q || r),
  },

  // --- Absorption & Redundancy Laws ---
  {
    id: 'absorption-or',
    name: 'Absorption Law (Disjunction)',
    category: 'Absorption',
    symbolicFormula: 'p ∨ (p ∧ q) ≡ p',
    lhs: 'p ∨ (p ∧ q)',
    rhs: 'p',
    tautologyExpression: '(p ∨ (p ∧ q)) ↔ p',
    variables: ['p', 'q'],
    meaning: 'In a disjunction where one term is a variable and the other is a conjunction containing it, the smaller term absorbs the larger.',
    intuition: 'If p is true, the statement is true. If p is false, both terms are false. Variable q has zero effect.',
    evalLhs: (p, q) => p || (p && q),
    evalRhs: (p) => p,
  },
  {
    id: 'absorption-and',
    name: 'Absorption Law (Conjunction)',
    category: 'Absorption',
    symbolicFormula: 'p ∧ (p ∨ q) ≡ p',
    lhs: 'p ∧ (p ∨ q)',
    rhs: 'p',
    tautologyExpression: '(p ∧ (p ∨ q)) ↔ p',
    variables: ['p', 'q'],
    meaning: 'In a conjunction where one term is a variable and the other is a disjunction containing it, p absorbs the rest.',
    intuition: 'If p is true, (p ∨ q) is also true, making the result true. If p is false, the conjunction is false.',
    evalLhs: (p, q) => p && (p || q),
    evalRhs: (p) => p,
  },

  // --- Basic Equivalences ---
  {
    id: 'double-negation',
    name: 'Double Negation Law',
    category: 'Basic Equivalences',
    symbolicFormula: '¬(¬p) ≡ p',
    lhs: '¬(¬p)',
    rhs: 'p',
    tautologyExpression: '¬(¬p) ↔ p',
    variables: ['p'],
    meaning: 'Negating a proposition twice returns the original truth value in classical propositional logic.',
    intuition: 'Not not true is simply true.',
    evalLhs: (p) => !(!p),
    evalRhs: (p) => p,
  },
  {
    id: 'idempotent-and',
    name: 'Idempotent Law (AND)',
    category: 'Basic Equivalences',
    symbolicFormula: 'p ∧ p ≡ p',
    lhs: 'p ∧ p',
    rhs: 'p',
    tautologyExpression: '(p ∧ p) ↔ p',
    variables: ['p'],
    meaning: 'Repeating a proposition with conjunction yields the exact same proposition.',
    intuition: 'Asserting "it is raining AND it is raining" provides no more information than "it is raining".',
    evalLhs: (p) => Boolean(p ? p : false),
    evalRhs: (p) => p,
  },
  {
    id: 'idempotent-or',
    name: 'Idempotent Law (OR)',
    category: 'Basic Equivalences',
    symbolicFormula: 'p ∨ p ≡ p',
    lhs: 'p ∨ p',
    rhs: 'p',
    tautologyExpression: '(p ∨ p) ↔ p',
    variables: ['p'],
    meaning: 'Repeating a proposition with disjunction yields the exact same proposition.',
    intuition: 'Saying "either it is raining or it is raining" is identical to saying "it is raining".',
    evalLhs: (p) => Boolean(p ? true : p),
    evalRhs: (p) => p,
  },
  {
    id: 'commutative-and',
    name: 'Commutative Law (Conjunction)',
    category: 'Basic Equivalences',
    symbolicFormula: 'p ∧ q ≡ q ∧ p',
    lhs: 'p ∧ q',
    rhs: 'q ∧ p',
    tautologyExpression: '(p ∧ q) ↔ (q ∧ p)',
    variables: ['p', 'q'],
    meaning: 'The order of operands in conjunction does not affect the truth value.',
    intuition: '"Alice and Bob" is true under the exact same conditions as "Bob and Alice".',
    evalLhs: (p, q) => p && q,
    evalRhs: (p, q) => q && p,
  },
  {
    id: 'commutative-or',
    name: 'Commutative Law (Disjunction)',
    category: 'Basic Equivalences',
    symbolicFormula: 'p ∨ q ≡ q ∨ p',
    lhs: 'p ∨ q',
    rhs: 'q ∨ p',
    tautologyExpression: '(p ∨ q) ↔ (q ∨ p)',
    variables: ['p', 'q'],
    meaning: 'The order of operands in disjunction does not affect the truth value.',
    intuition: '"Tea or coffee" is true under the same conditions as "coffee or tea".',
    evalLhs: (p, q) => p || q,
    evalRhs: (p, q) => q || p,
  },
  {
    id: 'associative-and',
    name: 'Associative Law (Conjunction)',
    category: 'Basic Equivalences',
    symbolicFormula: '(p ∧ q) ∧ r ≡ p ∧ (q ∧ r)',
    lhs: '(p ∧ q) ∧ r',
    rhs: 'p ∧ (q ∧ r)',
    tautologyExpression: '((p ∧ q) ∧ r) ↔ (p ∧ (q ∧ r))',
    variables: ['p', 'q', 'r'],
    meaning: 'Grouping does not matter when chaining conjunctions.',
    intuition: 'All three statements must be true for the conjunction to hold, regardless of how they are parenthesized.',
    evalLhs: (p, q, r) => (p && q) && r,
    evalRhs: (p, q, r) => p && (q && r),
  },
  {
    id: 'associative-or',
    name: 'Associative Law (Disjunction)',
    category: 'Basic Equivalences',
    symbolicFormula: '(p ∨ q) ∨ r ≡ p ∨ (q ∨ r)',
    lhs: '(p ∨ q) ∨ r',
    rhs: 'p ∨ (q ∨ r)',
    tautologyExpression: '((p ∨ q) ∨ r) ↔ (p ∨ (q ∨ r))',
    variables: ['p', 'q', 'r'],
    meaning: 'Grouping does not matter when chaining disjunctions.',
    intuition: 'At least one of the three statements must be true, regardless of grouping.',
    evalLhs: (p, q, r) => (p || q) || r,
    evalRhs: (p, q, r) => p || (q || r),
  },

  // --- Biconditional & XOR Laws ---
  {
    id: 'biconditional-definition',
    name: 'Biconditional as Mutual Implication',
    category: 'Biconditional & XOR',
    symbolicFormula: 'p ↔ q ≡ (p → q) ∧ (q → p)',
    lhs: 'p ↔ q',
    rhs: '(p → q) ∧ (q → p)',
    tautologyExpression: '(p ↔ q) ↔ ((p → q) ∧ (q → p))',
    variables: ['p', 'q'],
    meaning: 'Two statements are equivalent if and only if each implies the other.',
    intuition: 'In mathematical proofs, establishing an "if and only if" requires proving both directions.',
    evalLhs: (p, q) => p === q,
    evalRhs: (p, q) => (!p || q) && (!q || p),
  },
  {
    id: 'biconditional-normal-form',
    name: 'Biconditional Truth Form',
    category: 'Biconditional & XOR',
    symbolicFormula: 'p ↔ q ≡ (p ∧ q) ∨ (¬p ∧ ¬q)',
    lhs: 'p ↔ q',
    rhs: '(p ∧ q) ∨ (¬p ∧ ¬q)',
    tautologyExpression: '(p ↔ q) ↔ ((p ∧ q) ∨ (¬p ∧ ¬q))',
    variables: ['p', 'q'],
    meaning: 'A biconditional is true when both are True OR both are False.',
    intuition: 'p and q share the exact same truth state: either both hold, or neither holds.',
    evalLhs: (p, q) => p === q,
    evalRhs: (p, q) => (p && q) || (!p && !q),
  },
  {
    id: 'xor-definition',
    name: 'Exclusive OR (XOR) Definition',
    category: 'Biconditional & XOR',
    symbolicFormula: 'p ⊕ q ≡ (p ∨ q) ∧ ¬(p ∧ q)',
    lhs: 'p ⊕ q',
    rhs: '(p ∨ q) ∧ ¬(p ∧ q)',
    tautologyExpression: '(p ⊕ q) ↔ ((p ∨ q) ∧ ¬(p ∧ q))',
    variables: ['p', 'q'],
    meaning: 'XOR means at least one is true, but NOT both.',
    intuition: 'Standard colloquial English "either soup or salad, but not both".',
    evalLhs: (p, q) => p !== q,
    evalRhs: (p, q) => (p || q) && !(p && q),
  },
  {
    id: 'xor-dnf',
    name: 'XOR Disjunctive Normal Form',
    category: 'Biconditional & XOR',
    symbolicFormula: 'p ⊕ q ≡ (p ∧ ¬q) ∨ (¬p ∧ q)',
    lhs: 'p ⊕ q',
    rhs: '(p ∧ ¬q) ∨ (¬p ∧ q)',
    tautologyExpression: '(p ⊕ q) ↔ ((p ∧ ¬q) ∨ (¬p ∧ q))',
    variables: ['p', 'q'],
    meaning: 'XOR is true when p is true and q is false, or p is false and q is true.',
    intuition: 'Foundational circuit logic representation for half-adders.',
    evalLhs: (p, q) => p !== q,
    evalRhs: (p, q) => (p && !q) || (!p && q),
  },

  // --- Rules of Inference / Implication Tautologies ---
  {
    id: 'modus-ponens',
    name: 'Modus Ponens (Law of Detachment)',
    category: 'Rules of Inference',
    symbolicFormula: '((p → q) ∧ p) → q',
    lhs: '(p → q) ∧ p',
    rhs: 'q',
    tautologyExpression: '((p → q) ∧ p) → q',
    variables: ['p', 'q'],
    meaning: 'If a conditional statement and its hypothesis are true, its conclusion is necessarily true.',
    intuition: 'If you know "if it rains, I carry an umbrella" and you see it is raining, you know I carry an umbrella.',
    evalLhs: (p, q) => (!p || q) && p,
    evalRhs: (_, q) => q,
  },
  {
    id: 'modus-tollens',
    name: 'Modus Tollens (Denying the Consequent)',
    category: 'Rules of Inference',
    symbolicFormula: '((p → q) ∧ ¬q) → ¬p',
    lhs: '(p → q) ∧ ¬q',
    rhs: '¬p',
    tautologyExpression: '((p → q) ∧ ¬q) → ¬p',
    variables: ['p', 'q'],
    meaning: 'If a conditional holds and its conclusion is false, the hypothesis must be false.',
    intuition: 'If "raining implies wet ground" and the ground is dry, it cannot be raining.',
    evalLhs: (p, q) => (!p || q) && !q,
    evalRhs: (p) => !p,
  },
  {
    id: 'hypothetical-syllogism',
    name: 'Hypothetical Syllogism (Chain Rule)',
    category: 'Rules of Inference',
    symbolicFormula: '((p → q) ∧ (q → r)) → (p → r)',
    lhs: '(p → q) ∧ (q → r)',
    rhs: 'p → r',
    tautologyExpression: '((p → q) ∧ (q → r)) → (p → r)',
    variables: ['p', 'q', 'r'],
    meaning: 'Transitivity of implication: an unbroken chain of implications is valid.',
    intuition: 'If A leads to B and B leads to C, then A leads to C.',
    evalLhs: (p, q, r) => (!p || q) && (!q || r),
    evalRhs: (p, _, r) => !p || r,
  },
  {
    id: 'disjunctive-syllogism',
    name: 'Disjunctive Syllogism',
    category: 'Rules of Inference',
    symbolicFormula: '((p ∨ q) ∧ ¬p) → q',
    lhs: '(p ∨ q) ∧ ¬p',
    rhs: 'q',
    tautologyExpression: '((p ∨ q) ∧ ¬p) → q',
    variables: ['p', 'q'],
    meaning: 'If one of two possibilities must occur and one is eliminated, the other must be true.',
    intuition: 'Sherlock Holmes reasoning: once you eliminate the impossible, whatever remains, however improbable, must be the truth.',
    evalLhs: (p, q) => (p || q) && !p,
    evalRhs: (_, q) => q,
  },
];
